FROM rust:1.81-alpine

WORKDIR /app/backend

RUN apk add --no-cache musl-dev libressl-dev

# Copy the Cargo.toml files
RUN USER=root cargo init
COPY ./backend/Cargo.toml ./Cargo.toml
COPY ./backend/migration/Cargo.toml ./migration/Cargo.toml

# Fetch dependencies
RUN cargo fetch

