FROM rust:latest

WORKDIR /app

EXPOSE 8011

RUN apt-get update \
    && apt-get install -y libssl-dev \
    && apt-get install -y locales \
    && sed -i -e 's/# \(ja_JP.UTF-8\)/\1/' /etc/locale.gen \
    && locale-gen \
    && update-locale LANG=ja_JP.UTF-8 \
    && rustup component add rustfmt clippy

ENV LC_ALL ja_JP.UTF-8
ENV TZ Asia/Tokyo
ENV LANG=ja_JP.UTF-8
