services:
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile.remote
    container_name: ec-extension_backend
    ports:
      - "8011:8080"
    tty: true
    env_file:
      - "./backend/.env"

  backend-db:
    image: postgres:17.0-bookworm
    container_name: ec-extension_backend-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/migration/init:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres_data:
