//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

pub mod prelude;

pub mod permission;
pub mod resource;
pub mod role;
pub mod role_resource_permission;
pub mod test;
pub mod user;
pub mod user_role;
