//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub mod prelude;

pub mod permission;
pub mod resource;
pub mod role;
pub mod role_resource_permission;
pub mod user;
pub mod user_group;
pub mod user_group_role;
pub mod user_role;
pub mod user_user_group;
