//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

#![allow(unused_imports)]
pub use super::permission::Entity as Permission;
pub use super::resource::Entity as Resource;
pub use super::role::Entity as Role;
pub use super::role_resource_permission::Entity as RoleResourcePermission;
pub use super::user::Entity as User;
pub use super::user_group::Entity as UserGroup;
pub use super::user_group_role::Entity as UserGroupRole;
pub use super::user_role::Entity as UserRole;
pub use super::user_user_group::Entity as UserUserGroup;
