//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user_group")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::user_group_role::Entity")]
    UserGroupRole,
    #[sea_orm(has_many = "super::user_user_group::Entity")]
    UserUserGroup,
}

impl Related<super::user_group_role::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserGroupRole.def()
    }
}

impl Related<super::user_user_group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserUserGroup.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
